name: Daily Python Script

on:
  schedule:
    - cron: '0 2 * * 1-5'   # 09:00 WIB (09:00 WIB -> 02:00 UTC) - Pre-market
    - cron: '30 2 * * 1-5'  # 09:30 WIB (09:30 WIB -> 02:30 UTC) - Session 1 opens
    - cron: '0 3 * * 1-5'   # 10:00 WIB (10:00 WIB -> 03:00 UTC) - During Session 1
    - cron: '45 6 * * 1-5'  # 13:45 WIB (13:45 WIB -> 06:45 UTC) - 15 min after Session 2 opens
    - cron: '50 8 * * 1-5'  # 15:50 WIB (15:50 WIB -> 08:50 UTC) - Market close
  workflow_dispatch: # Allows manual run

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          TZ: 'Asia/Jakarta'
          TELEGRAM_TOKEN: '7827421978:AAE4NC3_ivtpqBqtJf_W2BTgSLtx_QDk5Y8'
          TELEGRAM_CHAT_ID: '5840594566'
        run: |
          python main.py
          sleep 30
          python main.py
